### ISSUE TITLE
Android PIP Issue  : MissingPluginException(No implementation found for method available on channel fl_pip)

### ISSUE THREAD

**Issue by foram0147** [Wayaer/fl_pip#11]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method available on channel fl_pip)
E/flutter (10052): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
E/flutter (10052): <asynchronous suspension>
E/flutter (10052): #1      FlPiP.isAvailable (package:fl_pip/fl_pip.dart:116:25)
E/flutter (10052): <asynchronous suspension>
E/flutter (10052): #2      _PiPBuilderState.initState.<anonymous closure> (package:fl_pip/fl_pip.dart:26:21)
E/flutter (10052): <asynchronous suspension>

I've called a method to check whether PIP is available or not 
 Future<void> requestPipAvailability() async {
    pipAvailable = await FlPiP().isAvailable;
    setState(() {});
  }

**Comment by Wayaer** [comment]
![image](https://github.com/Wayaer/fl_pip/assets/17231965/71227254-abc5-43ff-9b9f-456d6094ee81)

**Comment by foram0147** [comment]
Those configuration already done which are mentioned in readme file

**Comment by Wayaer** [comment]
Try updating to the latest version
